version: '3.9'
services:
  db:
    image: postgres:14.2-alpine3.15
    hostname: ${POSTGRES_HOSTNAME}
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d querky-db"]
      interval: 10s
  mq:
    image: rabbitmq:3-management
    hostname: rabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "61613:61613"
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
  app:
    image: querky:0.0.1
    depends_on:
      mq:
        condition: service_started
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - OAUTH2_CLIENT_ID
      - OAUTH2_CLIENT_SECRET
      - POSTGRES_HOSTNAME
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - RABBITMQ_HOSTNAME
      - RABBITMQ_PORT
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
